# Dimensionality Reduction with PCA

In [21]:
#Importing all libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import math
import os
from itertools import combinations
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report, make_scorer
from sklearn.utils.class_weight import compute_sample_weight
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA

In [22]:
print(os.getcwd())

c:\Users\ntama\Documentos\Data Science\Codecademy\projects\Date-A-Scientist - Final Project\OKCupid-Date-A-Scientist-Starter\date-a-scientist-project\notebooks


## Importing predictors and target - train, test and validation subsets

In [23]:
X_train = pd.read_csv("../data/X_train.csv", index_col=False)
X_train = X_train.loc[:, ~X_train.columns.str.contains('^Unnamed')]

X_val = pd.read_csv("../data/X_val.csv", index_col=False)
X_val = X_val.loc[:, ~X_val.columns.str.contains('^Unnamed')]

X_test = pd.read_csv("../data/X_test.csv", index_col=False)
X_test = X_test.loc[:, ~X_test.columns.str.contains('^Unnamed')]

y_train = pd.read_csv("../data/y_train.csv", index_col=False)
y_train = y_train.loc[:, ~y_train.columns.str.contains('^Unnamed')]

y_val = pd.read_csv("../data/y_val.csv", index_col=False)
y_val = y_val.loc[:, ~y_val.columns.str.contains('^Unnamed')]

y_test = pd.read_csv("../data/y_test.csv", index_col=False)
y_test = y_test.loc[:, ~y_test.columns.str.contains('^Unnamed')]

In [24]:
pca = PCA(n_components=0.95, random_state=42)  # o un número fijo de componentes
X_train_pca = pca.fit_transform(X_train)       # fit sólo con train
X_val_pca = pca.transform(X_val)               # transform con val y test
X_test_pca = pca.transform(X_test)

In [25]:
rf = RandomForestClassifier(class_weight='balanced', random_state=42, n_jobs=-1)
rf.fit(X_train_pca, y_train)

y_val_pred = rf.predict(X_val_pca)
print("Evaluación con PCA:")
print(classification_report(y_val, y_val_pred))
print(confusion_matrix(y_val, y_val_pred))

c:\Users\ntama\anaconda3\Lib\site-packages\sklearn\base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


Evaluación con PCA:
              precision    recall  f1-score   support

           0       0.53      0.53      0.53      4147
           1       0.41      0.29      0.34      3514
           2       0.22      0.39      0.28      1331

    accuracy                           0.42      8992
   macro avg       0.39      0.40      0.38      8992
weighted avg       0.44      0.42      0.42      8992

[[2197 1083  867]
 [1531 1030  953]
 [ 425  389  517]]


## Checking class imbalance

In [26]:
print(y_train.value_counts())

body_type
0            19354
1            16398
2             6210
Name: count, dtype: int64


Classes 2 and 3 are minoritarian.